### ISSUE TITLE
properties file is not loaded from classpath

### ISSUE THREAD

**Issue by HassanKadhem** [camunda/camunda-bpm-mail#12]
I have placed my 'mail-config.properties' in /src/main/resources yet when I run my process I get the following exception 
`java.lang.IllegalStateException: Cannot find mail configuration at: classpath:/mail-config.properties
	at org.camunda.bpm.extension.mail.config.PropertiesMailConfiguration.loadProperties(PropertiesMailConfiguration.java:122)
	at org.camunda.bpm.extension.mail.config.PropertiesMailConfiguration.getProperties(PropertiesMailConfiguration.java:106)
	at org.camunda.bpm.extension.mail.config.PropertiesMailConfiguration.getSender(PropertiesMailConfiguration.java:78)
	at org.camunda.bpm.extension.mail.send.SendMailRequest.getFrom(SendMailRequest.java:62)
`

I checked the classpath of my process which is /WEB-INF/classes/ and the properties file is there. am I missing a configuration? 

please note that I don't want to set the MAIL_CONFIG variable as I want each process to have a distinct mail-config.properties

**Comment by saig0** [comment]
Hi @HassanKadhem , 

do you use a shared process engine (e.g. tomcat distribution) ?

Currently, the mail configuration applies globally to all processes of the process engine. You can't have different configurations. However, this could be a good improvement.

Best regards,
Philipp

**Comment by HassanKadhem** [comment]
yes I'm currently testing my process on a shared process engine.

**Comment by HassanKadhem** [comment]
yes. 

I think there classpath of the each process should be the default path for mail-config.properties unless configured otherwise(setting MAIL_CONFIG environment variable if global configuration is desired)

**Comment by HassanKadhem** [comment]
sorry I completely forgot about this, I still want to work on it. 
I'm trying few things currently and I want to rebuild the connector, I ran: 
`mvn install -f pom.xml` and some tests are failing **camunda-bpm-mail-core** 

is this normal ? 

@saig0

**Comment by saig0** [comment]
Hey :wave: 

No. All tests should run fine. Do you work on the current `master` branch? 
I did some changes 2 weeks ago.

**Comment by HassanKadhem** [comment]
Sorry I forgot to pull 🤦‍♂️ 
I got the latest now ... still some tests are failing. most of them if not all are caused by SocketException 

is my build command correct?

**Comment by saig0** [comment]
Please share the test output. It should contain the failure and help to analyze it.

**Comment by HassanKadhem** [comment]
two tests have failed and one is skipped, i'm running `java 1.8.0_91`

first one is caused by this method `sendMailWithTextBody` from `org.camunda.bpm.extension.mail.send.SendMailConnectorProcessTest` and here is the stack trace: 

```
java.lang.IllegalStateException: Could not start mail server smtps:3465, try to set server startup timeout > 1000 via ServerSetup.setServerStartupTimeout(timeoutInMs)
	at com.icegreen.greenmail.util.GreenMail.start(GreenMail.java:102)
	at com.icegreen.greenmail.util.GreenMailProxy.start(GreenMailProxy.java:95)
	at com.icegreen.greenmail.junit.GreenMailRule$1.evaluate(GreenMailRule.java:52)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

second one is from this method `test` at `org.camunda.bpm.extension.mail.example.ProcessIntegrationTest` and here is the stack trace: 

```
java.lang.AssertionError: 
Expecting actual not to be empty
	at org.camunda.bpm.extension.mail.example.ProcessIntegrationTest.test(ProcessIntegrationTest.java:44)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.camunda.bpm.engine.test.ProcessEngineRule$1.evaluate(ProcessEngineRule.java:172)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
```

**Comment by saig0** [comment]
Ok. The test `ProcessIntegrationTest` has an `@Ignore` annotation because it is only for manual integration testing. So, it should not be executed.   

The test `SendMailConnectorProcessTest` failed because the mock server did not start (`Could not start mail server smtps:3465, try to set server startup timeout > 1000`). This is maybe a problem with your environment. You can check or try to increase the startup timeout as suggested.

**Comment by HassanKadhem** [comment]
do you have any idea where I can increase the timeout? I was looking at the code but I couldn't find where I might increase it. 

btw, shouldn't tests run the same everywhere regardless of environment?

**Comment by saig0** [comment]
I'm not sure if you can set the timeout using the JUnit rule. It seems there is an environment variable `-Dgreenmail.startup.timeout=2000`.

Yes, tests should run everywhere. I don't know why it is not working for you. They run in our CI without problems.
