### ISSUE TITLE
raising incidents on severe errors instead of discarding the process

### ISSUE THREAD

**Issue by HassanKadhem** [camunda/camunda-bpm-mail#15]
greetings, 

I have noticed while experimenting with the connector that in case of sever errors like this one: 

```SEVERE [ajp-nio-8009-exec-7] org.camunda.commons.logging.BaseLogger.logError ENGINE-16004 Exception while closing command context: failed to send mail
 org.camunda.bpm.extension.mail.MailConnectorException: failed to send mail
	at org.camunda.bpm.extension.mail.send.SendMailConnector.execute(SendMailConnector.java:65)
	at org.camunda.bpm.extension.mail.send.SendMailConnector.execute(SendMailConnector.java:38)
	at 
....
....
	at org.camunda.bpm.extension.mail.service.MailService.getTransport(MailService.java:91)
	at org.camunda.bpm.extension.mail.send.SendMailInvocation.invokeTarget(SendMailInvocation.java:45)
	at org.camunda.connect.impl.AbstractRequestInvocation.proceed(AbstractRequestInvocation.java:60)
	at org.camunda.bpm.extension.mail.send.SendMailConnector.execute(SendMailConnector.java:62)
	... 131 more
```

the process gets discarding rather than having an incident raised. is this a normal thing? I think the process shouldn't be discarded/canceled if a service task performing mail-send fails for whatever reason. This critical as it leads to loss of information which also leads to other complications.

**Comment by saig0** [comment]
Hi @HassanKadhem , 

this is expected behavior and nothing special about the connector. You should mark the activity as _asynchronous before_. So the engine will retry or create an incident.
